runtime: python39 
instance_class: F2
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  BUCKET_NAME: "asm-app-bucket"

handlers:
- url: /img
  static_dir: static/img

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto